chart/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include("todo.urls")),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path, include
from . import views

app_name='todo'

urlpatterns=[
    path('add/', views.add, name="add"),
    path('liste/', views.liste, name="liste"),
    path('delete/<int:num>/', views.delete, name="delete"),
    path('draw/', views.draw, name="draw"),
]

todo/models.py
from django.db import models

# Create your models here.

from django.utils import timezone

#The information related to the car
class car_info(models.Model):

    #The brand (using letters)
    brand = models.CharField(max_length=50)

    #The consumption(a number)
    consommation = models.DecimalField(default=0, decimal_places=1, max_digits=3)
    def __str__(self):
        
        #When I call an object, the brand is going to show
        return self.brand

todo/forms.py
from django.forms import ModelForm
from .models import car_info
from django import forms


class forme(ModelForm):
    class Meta:

        #Affect the model "car_info"
        model=car_info
        fields=['brand', 'consommation']
        queryset=car_info.objects.all()

todo/views.py
from django.shortcuts import render

# Create your views here.

from .forms import forme
from .models import car_info
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone


#what happens when we click add
def add(request):

    #After the user clicks "add"
    form=forme(request.POST)
    if form.is_valid():
        if float(request.POST["consommation"]) >= 0:
            #The form is a model form, it will automatically save the information
            form.save()
        else:
            return render(request, 'todo/liste.html', {'liste':car_info.objects.all(), 'form':forme(), 'error': "Consommation must be a positive number", })

        #Return to list after adding
    return HttpResponseRedirect(reverse('todo:liste'))
    

def liste(response):
    #What to display at first
    return render(response, 'todo/liste.html', {'form':forme(), 'liste':car_info.objects.all()})

def delete(request, num):
    #num is the car_info rank, used as an argument
    car_info.objects.get(pk=num).delete()

    #after deleting, come back to the liste page
    return HttpResponseRedirect(reverse('todo:liste'))

def draw(request):

    #Use js to draw a bar chart
    label = []
    data = []
    for a in car_info.objects.all():
        label.append(a.brand)
        data.append(float(a.consommation))
    return render(request, 'todo/chart.html', {'labels':label, 'data':data})
        
    

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="author" content="Minohery">
<meta content="description" content="To-do app">
{% block link %}{% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html> 

todo/templates/todo/chart.html
{% extends 'todo/base.html' %}

{% block link %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
{% endblock %}

{% block content %}
<canvas id="myChart" width="400" height="400"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: {{ labels|safe }},
        datasets: [{
            label: 'Consommation',
            data: {{ data|safe }},
            backgroundColor: 'blue',
            borderWidth: 1,
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

{% endblock %}

todo/templates/todo/liste.html
{% extends 'todo/base.html' %}
{% block link %}<link rel="stylesheet" href='/static/todo/bootstrap.css' type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="/static/todo/query.js"></script>
{% endblock %}

{% block content %}
<h1>Cars and consumption</h1>
<ol>
{% for a in liste %}
<form action="{% url 'todo:delete' a.pk %}" method="POST">
{% csrf_token %}
<li>{{ a }} , Consommation : {{ a.consommation }} L/100;</li>
<input type="submit" value="Done">


</form>
{% endfor %}
</ol>
<table>

{# These classes will allow bootstrap 4 to recognize and design the form #}
<div class="container">
<div class="row">
<div class="col"> 
<form action="{% url 'todo:add' %}" method="POST">
{% csrf_token %}
{{ form.as_table }}
</div>
</div>
</div>

</table>
{# This class will allow bootstrap4 to recognize and design the button #}
<input class="btn btn-success" type="submit" value="Add">

</form>

{% if liste.count >= 1 %}

<form action="{% url 'todo:draw' %}" method="POST">
{% csrf_token %}
<input type="submit" value="Draw the graph">
</form>

{% endif %}
{% if error %}
{{ error }}
{% endif %}

{% endblock %}